"""
intel.py — Per-location pre-call intelligence.

compute_location_intel(location_id, company_id) is the public entrypoint. It
recomputes every column on the location_intel row for (location, company):
the rolling stats (last call info, total/avg/no-answer counts) plus an AI
brief (summary, strengths, weaknesses) generated by Claude.

Always runs in a daemon background thread — never block the grade response.
Use compute_location_intel_async() from request handlers.

Tenant scope: the SQL filters on locations.company_id so this never leaks
across tenants. The route layer is responsible for verifying that the
caller's company owns the location before invoking this.
"""

import json
import logging
import os
import threading

import anthropic

from db import IS_POSTGRES, get_conn, q
from helpers import check_rate_limit, increment_usage

logger = logging.getLogger(__name__)

_claude = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

# status_id 44 = no_answer, 43 = graded — keep in sync with statuses seed.
_STATUS_NO_ANSWER = 44
_STATUS_GRADED    = 43


def _row_to_dict(row):
    if row is None:
        return None
    try:
        return dict(row)
    except Exception:
        return {k: row[k] for k in row.keys()}


def compute_location_intel_async(location_id, company_id):
    """Fire-and-forget background refresh. Safe to call from request handlers."""
    if not location_id or not company_id:
        return
    t = threading.Thread(
        target=_compute_safe,
        args=(location_id, company_id),
        daemon=True,
    )
    t.start()


def _compute_safe(location_id, company_id):
    try:
        compute_location_intel(location_id, company_id)
    except Exception:
        logger.exception(
            "Background location intel update failed (location=%s company=%s)",
            location_id, company_id,
        )


def compute_location_intel(location_id, company_id):
    """Refresh the location_intel row for (location, company).

    Pulls every non-deleted interaction whose project's campaign or rubric
    group resolves to this location, computes rolling stats, and asks Claude
    for an updated brief. Upserts the row and sets li_last_computed_at.

    Skips the Claude call (and leaves AI columns NULL) when there are no
    graded calls — only no-answers or no calls at all.
    """
    conn = get_conn()
    try:
        # Pull all interactions for this location via either join path.
        # Projects can resolve location through campaigns OR rubric_groups,
        # so COALESCE through both.
        cur = conn.execute(q("""
            SELECT
                i.interaction_id,
                i.interaction_date,
                i.interaction_call_start_time,
                i.interaction_uploaded_at,
                i.interaction_overall_score,
                i.interaction_strengths,
                i.interaction_weaknesses,
                i.interaction_overall_assessment,
                i.status_id
              FROM interactions i
              JOIN projects     p  ON p.project_id      = i.project_id
              LEFT JOIN campaigns     c  ON c.campaign_id    = p.campaign_id
              LEFT JOIN rubric_groups rg ON rg.rubric_group_id = p.rubric_group_id
             WHERE COALESCE(c.location_id, rg.location_id) = ?
               AND p.company_id = ?
               AND i.interaction_deleted_at IS NULL
             ORDER BY i.interaction_id DESC
        """), (location_id, company_id))
        rows = [_row_to_dict(r) for r in cur.fetchall()]
    finally:
        conn.close()

    total_calls      = len(rows)
    no_answer_count  = sum(1 for r in rows if r["status_id"] == _STATUS_NO_ANSWER)
    scored = [
        r for r in rows
        if r["status_id"] != _STATUS_NO_ANSWER
        and r.get("interaction_overall_score") is not None
    ]
    avg_score = (
        round(sum(float(r["interaction_overall_score"]) for r in scored) / len(scored), 2)
        if scored else None
    )

    # Last call: the most recent GRADED interaction only. Rows still in
    # awaiting_clarification / grading have no score yet and shouldn't masquerade
    # as "the last call" on the pre-call briefing. No-answer counts are tracked
    # separately via li_no_answer_count.
    last = next((r for r in rows if r["status_id"] == _STATUS_GRADED), None)
    last_call_date    = last["interaction_date"] if last else None
    last_call_time    = (
        last.get("interaction_call_start_time") or last.get("interaction_uploaded_at")
        if last else None
    )
    last_call_score   = (
        float(last["interaction_overall_score"])
        if last and last.get("interaction_overall_score") is not None else None
    )
    last_call_outcome = "graded" if last else None

    summary = strengths = weaknesses = None
    if scored:
        ai = _generate_brief(scored)
        if ai:
            summary    = ai.get("summary")    or None
            strengths  = ai.get("strengths")  or None
            weaknesses = ai.get("weaknesses") or None
        # AI call may have been skipped (rate-limited). Preserve prior brief if so.
        if ai is None:
            existing = _fetch_existing(location_id, company_id)
            if existing:
                summary    = existing.get("li_summary")
                strengths  = existing.get("li_strengths")
                weaknesses = existing.get("li_weaknesses")

    _upsert(
        location_id, company_id,
        last_call_date=last_call_date,
        last_call_time=last_call_time,
        last_call_score=last_call_score,
        last_call_outcome=last_call_outcome,
        total_calls=total_calls,
        avg_score=avg_score,
        no_answer_count=no_answer_count,
        summary=summary,
        strengths=strengths,
        weaknesses=weaknesses,
    )


def _fetch_existing(location_id, company_id):
    conn = get_conn()
    try:
        cur = conn.execute(
            q("""SELECT li_summary, li_strengths, li_weaknesses
                   FROM location_intel
                  WHERE location_id = ? AND company_id = ?"""),
            (location_id, company_id),
        )
        return _row_to_dict(cur.fetchone())
    finally:
        conn.close()


def _upsert(location_id, company_id, **fields):
    """Upsert the location_intel row. Sets li_last_computed_at = NOW()."""
    conn = get_conn()
    try:
        if IS_POSTGRES:
            conn.execute(
                """INSERT INTO location_intel (
                       location_id, company_id,
                       li_last_call_date, li_last_call_time,
                       li_last_call_score, li_last_call_outcome,
                       li_total_calls, li_avg_score, li_no_answer_count,
                       li_summary, li_strengths, li_weaknesses,
                       li_last_computed_at
                   ) VALUES (
                       %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW()
                   )
                   ON CONFLICT (location_id, company_id) DO UPDATE SET
                       li_last_call_date    = EXCLUDED.li_last_call_date,
                       li_last_call_time    = EXCLUDED.li_last_call_time,
                       li_last_call_score   = EXCLUDED.li_last_call_score,
                       li_last_call_outcome = EXCLUDED.li_last_call_outcome,
                       li_total_calls       = EXCLUDED.li_total_calls,
                       li_avg_score         = EXCLUDED.li_avg_score,
                       li_no_answer_count   = EXCLUDED.li_no_answer_count,
                       li_summary           = EXCLUDED.li_summary,
                       li_strengths         = EXCLUDED.li_strengths,
                       li_weaknesses        = EXCLUDED.li_weaknesses,
                       li_last_computed_at  = NOW()
                """,
                (
                    location_id, company_id,
                    fields["last_call_date"], fields["last_call_time"],
                    fields["last_call_score"], fields["last_call_outcome"],
                    fields["total_calls"], fields["avg_score"], fields["no_answer_count"],
                    fields["summary"], fields["strengths"], fields["weaknesses"],
                ),
            )
        else:
            conn.execute(
                """INSERT OR REPLACE INTO location_intel (
                       location_id, company_id,
                       li_last_call_date, li_last_call_time,
                       li_last_call_score, li_last_call_outcome,
                       li_total_calls, li_avg_score, li_no_answer_count,
                       li_summary, li_strengths, li_weaknesses,
                       li_last_computed_at
                   ) VALUES (
                       ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP
                   )""",
                (
                    location_id, company_id,
                    fields["last_call_date"], fields["last_call_time"],
                    fields["last_call_score"], fields["last_call_outcome"],
                    fields["total_calls"], fields["avg_score"], fields["no_answer_count"],
                    fields["summary"], fields["strengths"], fields["weaknesses"],
                ),
            )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _generate_brief(scored_calls):
    """Ask Claude for summary/strengths/weaknesses across the scored calls.

    Returns dict with keys summary/strengths/weaknesses, or None if the AI
    call was skipped (rate limit) or failed.
    """
    if not scored_calls:
        return None

    # We need any scored row's company to bill the rate limiter; the caller
    # already has it but it isn't passed here — derive from the first call's
    # interaction by re-querying. To avoid that round-trip we just rely on
    # the rate limit check at update time using a lookup-by-interaction.
    # Simpler: scored_calls don't carry company_id, so we charge nothing for
    # the rate-limit gate here and rely on the per-grade gate already paid.
    # But spec says "Check and increment anthropic rate limit before the
    # Claude call" — read company_id from the first row's interaction.
    # We don't have it on the row. Fall back to grabbing it via SQL.
    company_id = _company_for_interaction(scored_calls[0]["interaction_id"])
    if company_id is None:
        return None
    ok, _msg = check_rate_limit(company_id, "anthropic")
    if not ok:
        logger.warning("Skipping location intel brief — anthropic rate limit hit (company=%s)", company_id)
        return None

    history_block = "\n\n".join(
        f"Call on {c.get('interaction_date')} | Score: {c.get('interaction_overall_score')}/10\n"
        f"Strengths: {c.get('interaction_strengths') or '—'}\n"
        f"Weaknesses: {c.get('interaction_weaknesses') or '—'}\n"
        f"Assessment: {c.get('interaction_overall_assessment') or '—'}"
        for c in scored_calls[:25]  # cap context size
    )

    prompt = (
        "You are summarizing the call history for a single location to brief "
        "a caller before they dial. Read the graded calls below and produce a "
        "compact pre-call brief.\n\n"
        "REQUIREMENTS:\n"
        "- summary: 2-3 sentence plain English brief of what to expect when calling. "
        "Written as a heads-up before they dial. Mention what the staff is typically "
        "like, recurring problems, and recent trends if obvious.\n"
        "- strengths: 2-4 bullet points of consistent strengths across calls. "
        "Each on its own line starting with '• '.\n"
        "- weaknesses: 2-4 bullet points of consistent weaknesses across calls. "
        "Each on its own line starting with '• '.\n\n"
        f"CALL HISTORY ({len(scored_calls)} graded call(s)):\n{history_block}\n\n"
        "Respond with valid JSON only — no extra prose:\n"
        "{\n"
        '  "summary": "...",\n'
        '  "strengths": "• bullet\\n• bullet",\n'
        '  "weaknesses": "• bullet\\n• bullet"\n'
        "}"
    )

    try:
        response = _claude.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=1200,
            temperature=0,
            messages=[{"role": "user", "content": prompt}],
            timeout=60.0,
        )
        raw = response.content[0].text.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        data = json.loads(raw.strip())
    except Exception:
        logger.exception("Location intel Claude call failed")
        return None

    increment_usage(company_id, "anthropic")
    return {
        "summary":    (data.get("summary")    or "").strip() or None,
        "strengths":  (data.get("strengths")  or "").strip() or None,
        "weaknesses": (data.get("weaknesses") or "").strip() or None,
    }


def _company_for_interaction(interaction_id):
    conn = get_conn()
    try:
        cur = conn.execute(
            q("""SELECT p.company_id FROM interactions i
                   JOIN projects p ON p.project_id = i.project_id
                  WHERE i.interaction_id = ?"""),
            (interaction_id,),
        )
        row = _row_to_dict(cur.fetchone())
    finally:
        conn.close()
    return row.get("company_id") if row else None
